### ISSUE TITLE
Allow export of MIDI and sysex data in MIDI export

### ISSUE THREAD

**Issue by defensem3ch** [samlletas/syxg50-control-panel#13]
This plugin is so useful for composing in REAPER but is there still really no way to export the MIDI control or sysex data? It's practically useless if you want to export the XG MIDI data to play on hardware for instance. Otherwise, really neat tool, but please make this possible!

**Comment by samlletas** [comment]
As far as I know there is no way for a JSFX plugin to export MIDI automatically during a MIDI export, but what you could do is record the plugin's [sysex output](https://forums.cockos.com/showthread.php?t=176354) and export the MIDI file afterwards:

1. Right click on the track's record button and set it to `Record: output (MIDI)`. 
2. Start recording.
3. Click on the "XG" button (located at the top-right of the plugin's window) to force re-send all the plugin's sysex data.
4. Stop recording.

**Comment by defensem3ch** [comment]
This is a perfectly acceptable workaround for me - that's exactly what I needed, thank you so much!!
