### ISSUE TITLE
Suggestion: Add support for even more XG parameters

### ISSUE THREAD

**Issue by mkruselj** [samlletas/syxg50-control-panel#2]
Reading the XG specification, these parameters would be pretty cool to add to the control panel:

06  Same Note Number Key On Assign

Checkboxes instead of sliders would be best for these probably:

30 Receive Pitch Bend
31 Receive Channel Aftertouch
32 Receive Program Change
33 Receive Control Change
34 Receive Poly Aftertouch
35 Receive Note Message
36 Receive RPN
37 Receive NRPN
38 Receive Modulation
39 Receive Volume
3A Receive Pan
3B Receive Expression
3C Receive Hold Pedal
3D Receive Portamento
3E Receive Sostenuto
3F Receive Soft Pedal
40 Receive Bank Select

Thanks!

**Comment by samlletas** [comment]
Sounds good, with these parameters I think the control panel would cover almost everything (at least the stuff supported by the S-YXG50) except Drum Setup.

For simplicity's sake I would probably add these as sliders initially and then implement checkboxes in a different task/issue (#4).

Would a new sub-category named "Control" make sense for these parameters?

**Comment by mkruselj** [comment]
I would call the tab MIDI Filters personally!

**Comment by mkruselj** [comment]
PR I've opened now also supports these parameters too!

**Comment by samlletas** [comment]
Awesome! Thank you!
