### ISSUE TITLE
Bug: Cursor goes out of bounds in "Variation" tab

### ISSUE THREAD

**Issue by samlletas** [samlletas/syxg50-control-panel#3]
This happens when using the mouse wheel, ideally the entries should automatically scroll when moving past the first/last element.

Detected by @mkruselj:
https://www.kvraudio.com/forum/viewtopic.php?p=8911222#p8911222

**Comment by samlletas** [comment]
Fixed in https://github.com/samlletas/syxg50-control-panel/commit/0a8946819373d5e7ed8b09ae50c04f8eca7cdc2f

**Comment by mkruselj** [comment]
Works great, thank you!
