### ISSUE TITLE
Better value display for Detune and 14-bit delay time parameters

### ISSUE THREAD

**Issue by mkruselj** [samlletas/syxg50-control-panel#5]
I wonder if there is a way this could be improved so that user can see the actual real-world values (so for Detune this would be -12.8 Hz to +12.7 Hz - 256 values instead of 4096 values), and for delays it's a whole other ballgame)...

I don't have any ideas for this as it stands, but it does seem like a massive string table is NOT a good way to go, for obvious reasons... These parameters being sent as nibbles rather than a direct value complicates everything...

**Comment by mkruselj** [comment]
Oh, I may have gotten an idea just now. Based on [this very useful page](http://www.studio4all.de/htmle/main97.html#xgprgref11).

What if we make the slider have an actual linear real-world value range? So for Detune, instead of 0-4096, we make it -128-127, for display we divide it by 10 and append Hz for unit, and then do the required MSB/LSB nibblizing calculation to get the value we send out with `sysex_add_queue_multipart` function?

**Comment by samlletas** [comment]
Oh this is interesting, so detune value range is not 0-4096 but actually 0-255 nibblized, it now makes sense why XGworks was mapping the maximum possible value of 12.7Hz to 0F 0F (3855 decimal), I wrongly assumed it was the full range of values and ended up using 4096 as the max just to keep the default 08 00 (2048 decimal) at the center.

Some examples of sysex values sent by XGworks:

-12.8 Hz = 00 00 (0 decimal)
-7.1 Hz = 03 09 (777 decimal)
0.0 Hz = 08 00 (2048 decimal)
10.5 Hz = 0E 09 (3593 decimal)
12.7 Hz = 0F 0F (3855 decimal)

I like the idea of using -128 to 127 for detune, we might need to add +128 to that slider value when doing the calculations to keep it inside the 0-255 range and then nibble it, for example:

1. User selects 12.7 Hz in the UI (which maps to **127**)
2. **127** + 128 = 255 = 0xFF
3. And finally nibble it: 0F 0F

The downside of doing this is that it would break compatibility when loading data from previous versions of the control panel (v2.5 or older), however I think your approach to handle detune is better than the current implementation so perhaps we can label these changes as a v3 release, leaving users the choice of v2 for old projects.

**Comment by samlletas** [comment]
Hmm it seems delays may be possible too, for example XGworks does the following for Delay LCR >Lch Delay:

0.1 ms = 00 01 (1 decimal)
200.0 ms = 0F 50 (3920 decimal)
333.3 ms = 1A 05 (6661 decimal)
574.8 ms = 2C 74 (11380 decimal)
715.0 ms = 37 6E (14190 decimal)

So using ranges from 1-7150 and based on the page you found, if the user selects 200ms for example:

MSB = 2000 / 128 = **15** = 0x0F
LSB = 2000 - (**15** x 128) = 80 = 0x50

The result for 200 ms is 0F 50 which matches XGworks!

**Comment by mkruselj** [comment]
Yes, delay times work very similar to tuning calculation. I also agree since this is a breaking change it warrants a v3 :)

**Comment by mkruselj** [comment]
I would suggest though that it is probably good to first merge the currently open PR and call it a 2.6 (I hope I didn't do anything that would break streaming... does order of file_var() lines in @serialize block matter?), then a v3.0 which does these params properly. What do you think?

**Comment by samlletas** [comment]
Yes, the order of file_var in @serialize matters, but you know what, I like how the parameters are now properly organized so I'm considering including the PR in v3. Finished reviewing the PR and added some minor comments but overall everything looks good!

**Comment by samlletas** [comment]
Closed by 748b8e2e8b369952bc026b508dc78a86658d0c9d and 53633845a9d04a5a786aa622221fd9886fd0c541

Thanks again @mkruselj, the info you shared was key for completing this!
