### ISSUE TITLE
Feat: Merge both "Sound Effects" banks into a single bank

### ISSUE THREAD

**Issue by samlletas** [samlletas/syxg50-control-panel#6]
The improvements from PR https://github.com/samlletas/syxg50-control-panel/pull/1 made me realize that it's redundant to have 2 SFX Banks, it would be nice to merge them.

This is a breaking change so it may be a good idea to include in v3 release.

**Comment by mkruselj** [comment]
100%!

**Comment by samlletas** [comment]
Closed in https://github.com/samlletas/syxg50-control-panel/commit/d95dfbe642d0d5d9dbaaba062aa8688d7dc98f20
