### ISSUE TITLE
Slider behavior improvement suggestion

### ISSUE THREAD

**Issue by mkruselj** [samlletas/syxg50-control-panel#8]
The way sliders work now is a bit dangerous. If you start a click then drag away and you end up dragging over other sliders, you change their values too. Ideally user should be able to drag anywhere after clicking on a slider, and the value would only be changed for the slider that was clicked, and no other.

I'm not exactly sure how to code this up, which is why I'm just noting it down here. :)

**Comment by samlletas** [comment]
Closed by 276dfb266d1eecfc154e07d9f71c85b682fb4a8d
